### PR TITLE
Merge pull request #29 from EBI-Metagenomics/dev

### PR DESCRIPTION
**Pull request by Viromic**
Dev

### CODE REVIEW

**Review by hoelzer — APPROVED** [review]
Looks fine for me! Just some small changes to the profile handling of Nextflow. 

I'm just wondering, because I know that Guillermo also added some changes to the voting system recently but maybe that is in another branch. I will check this and start a PR if I can find it (because we anyway need these changes to re-run the pipeline for the current manuscript)

**Comment by mberacochea** [comment]
> Looks fine for me! Just some small changes to the profile handling of Nextflow.
> 
> I'm just wondering, because I know that Guillermo also added some changes to the voting system recently but maybe that is in another branch. I will check this and start a PR if I can find it (because we anyway need these changes to re-run the pipeline for the current manuscript)

Sure, one the CWL tests is failing. Before mering this I'll take a look at those.

**Comment by mberacochea** [comment]
I'm merging this, I'll fix the failling test in the docker branch anyway.

**Comment by hoelzer** [comment]
yip great, thx

**Pull request merged**
