### PR TITLE
Cwl docker

### PR DESCRIPTION
**Pull request by mberacochea**
This ended up in a massive PR.

Docker containers in microbiome informatics docker account. 
Some fixes in CWL, HMMER was bugged :(.
Nextflow include syntax change to do deprecation warning.

### CODE REVIEW

**Comment by mberacochea** [comment]
@hoelzer I've updated the containers and tested the nextflow version with the kleiner_2015 dataset. It seems to work.

Containers with different versions in dev compared to cwl-docker, they are just minor versions so I think it should be fine:

- multiqc (CWL - 1.9 | NF - 1.8)
- phanotate (CWL - 1.5.0 | NF - 1.2.2)

**Comment by mberacochea** [comment]
Results for kleiner_2015 => https://oc.ebi.ac.uk/s/EKmHNCY8A0y5Y3t

**Comment by hoelzer** [comment]
> Results for kleiner_2015 => https://oc.ebi.ac.uk/s/EKmHNCY8A0y5Y3t

@mberacochea awesome! Differences in the version for multiQC and phanotate are no problem at all. Both tools are currently not used in the main pipeline. 

I would like to run some checks by myself and reply to this PR soonish!

**Comment by mberacochea** [comment]
> > Results for kleiner_2015 => https://oc.ebi.ac.uk/s/EKmHNCY8A0y5Y3t
> 
> @mberacochea awesome! Differences in the version for multiQC and phanotate are no problem at all. Both tools are currently not used in the main pipeline.
> 
> I would like to run some checks by myself and reply to this PR soonish!

Brilliant. We can merge after checking the output :+1:

**Comment by hoelzer** [comment]
@mberacochea I think you are using an old assembly for Kleiner. At some point, I decided together w/ @guille0387 to re-do the assembly and throw out some samples with low viral amount. Please find attached the Kleiner co-assembly we are actually using now in the manuscript. 

I just observed this because your contig IDs are different in comparison to mine. I don't think you necessarily have to rerun the test for the current PR because basically everything is working, it's just another input FASTA. 

[kleiner_virome_2015.fasta.gz](https://github.com/EBI-Metagenomics/emg-viral-pipeline/files/5797571/kleiner_virome_2015.fasta.gz)
md5 `7a12ed9ce7eeb68e292c1ab7e580d447  kleiner_virome_2015.fasta`

I also run a test now for Kleiner: 
```
nextflow run virify.nf --fasta kleiner_virome_2015.fasta -w work -profile local,docker --cores 3 --max_cores 6 --length 1.5 --virome
```

that was working fine and producing the same results as what we had before. 

I just will go through the code changes as well and then approve the merge!

**Comment by mberacochea** [comment]
> @mberacochea I think you are using an old assembly for Kleiner. At some point, I decided together w/ @guille0387 to re-do the assembly and throw out some samples with low viral amount. Please find attached the Kleiner co-assembly we are actually using now in the manuscript.
> 
> I just observed this because your contig IDs are different in comparison to mine. I don't think you necessarily have to rerun the test for the current PR because basically everything is working, it's just another input FASTA.
> 
> [kleiner_virome_2015.fasta.gz](https://github.com/EBI-Metagenomics/emg-viral-pipeline/files/5797571/kleiner_virome_2015.fasta.gz)
> md5 `7a12ed9ce7eeb68e292c1ab7e580d447 kleiner_virome_2015.fasta`
> 
> I also run a test now for Kleiner:
> 
> ```
> nextflow run virify.nf --fasta kleiner_virome_2015.fasta -w work -profile local,docker --cores 3 --max_cores 6 --length 1.5 --virome
> ```
> 
> that was working fine and producing the same results as what we had before.
> 
> I just will go through the code changes as well and then approve the merge!

Brilliant! I had a that dataset lying around, I'll update it thanks!.

I'll merge this PR then :+1:

**Comment by mberacochea** [comment]
Ops, I merge it before reading this: `I just will go through the code changes as well and then approve the merge!`.

Anyway, @hoelzer  please add any comments on this merged PR

**Comment by hoelzer** [comment]
> Ops, I merge it before reading this: `I just will go through the code changes as well and then approve the merge!`.
> 
> Anyway, @hoelzer please add any comments on this merged PR

no problem! I anyway have a very tight schedule currently and so would only had a rough look :)

So with all the changes in `dev`, we might also have a PR for `master` with a new release?

**Pull request merged**
