### PR TITLE
Fix the Chromomap container.

### PR DESCRIPTION
**Pull request by mberacochea**

### CODE REVIEW

**Comment by mberacochea** [comment]
BTW we don't have to make a new release, as I've pushed the container to quay already.

**Comment by hoelzer** [comment]
Nice, works! I will merge this directly and yes, we can skip the release bc the container has the same name.

**Comment by hoelzer** [comment]
Ah, I think we still have to merge from `dev` into `master` now

**Review by hoelzer — COMMENTED** [review]
+1

**Pull request merged**
